FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY catalog-service/pom.xml .
RUN mvn dependency:go-offline -B
COPY catalog-service/src ./src
RUN mvn clean package -DskipTests

FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8084
ENTRYPOINT ["java", "-jar", "app.jar"]
