spring.application.name=api-gateway
server.port=${SERVER_PORT:8080}

AUTH_SERVICE_URL=http://localhost:8081
APPOINTMENT_SERVICE_URL=http://localhost:8082
CLINICAL_SERVICE_URL=http://localhost:8083

spring.cloud.gateway.routes[0].id=static-css
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/css/**

spring.cloud.gateway.routes[1].id=static-js
spring.cloud.gateway.routes[1].uri=${APPOINTMENT_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/js/**

spring.cloud.gateway.routes[2].id=auth-service
spring.cloud.gateway.routes[2].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/auth/**,/web/login,/web/dashboard,/web/users,/web/logout

spring.cloud.gateway.routes[3].id=appointment-service
spring.cloud.gateway.routes[3].uri=${APPOINTMENT_SERVICE_URL}
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/appointments/**,/web/appointments/**,/web/patients/**,/web/doctors/**,/api/patients/**,/api/doctors/**

spring.cloud.gateway.routes[4].id=clinical-service
spring.cloud.gateway.routes[4].uri=${CLINICAL_SERVICE_URL}
spring.cloud.gateway.routes[4].predicates[0]=Path=/api/clinical/**,/web/clinical/**

spring.cloud.gateway.routes[5].id=root-redirect
spring.cloud.gateway.routes[5].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[5].predicates[0]=Path=/
spring.cloud.gateway.routes[5].filters[0]=SetPath=/web/login
